baseURL = "https://agrofims.github.io/helpdocs/"
languageCode = "en-us"
title = "AgroFIMS Help Documentation"
theme = "dot-hugo-documentation-theme-master"
canonifyURLs = true
publishDir = "docs"


pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = true # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window

# toc = true                                                                            # 是否开启目录
# autoCollapseToc = true  # Auto expand and collapse toc                              # 目录自动展开/折叠
 
# logo is for all page
logo = "AgroFIMS help documentation"
bg_image = "images/logo.jpg"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#869910"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#agrofims@cgiar.org" # contact form works with : https://formspree.io


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS"]

[[menu.shortcuts]]
name = "<button class='btn btn-success mt-n1'>AgroFIMS</button>"
url = "https://agrofims.org/"
weight = 3

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/AGROFIMS/"
weight = 20

sectionPagesMenu = "main"




############################## social links ##############################
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#https://github.com/AGROFIMS"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#https://www.youtube.com/channel/UChfp4kWQCscsIUP-4duKzeQ/"
  
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright © AgroFIMS 2020 [Terms of Use and Privacy Policy](https://agrofims.github.io/helpdocs/policyterms/)"

# banner
[Languages.en.params.banner]
title = "AgroFIMS help documentation"
subtitle = "Find advice to create your own fieldbooks or get in touch"
bg_image = "images/banner.png"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = ""
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "agrofims@cgiar.org"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = ""
weight = 1

[[Languages.en.menu.main]]
name = "AgroFIMS"
url = "https://agrofims.org/"
weight = 2

[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 3


  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "choice"
  url = "billing-pricing"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3


