baseURL = "https://agrofims.github.io/helpdocs/"
languageCode = "en-us"
title = "AgroFIMS Help Documentation"
theme = "ace-documentation-1.0.4"
publishDir = "docs"


pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = false # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<button class='btn btn-success mt-n1'>AgroFIMS</button>"
url = "https://research.cip.cgiar.org/agrofims/dev/0212"
weight = 3

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/AGROFIMS/"
weight = 20